---
- name: Check status of docker service
  ansible.builtin.service_facts:

- name: Stop execution if docker service not running
  ansible.builtin.fail:
    msg: >
      minikube driver selected as docker but docker service is not running
  when:
    - minikube_driver == "docker" and ansible_facts.services["docker.service"].state == "stopped"

- block:
  - name: Get latest version number from github
    ansible.builtin.set_fact:
       _latest: "{{ lookup('url', 'https://storage.googleapis.com/kubernetes-release/release/stable.txt') | string }}"
    run_once: true
  - name: Show latest version number
    ansible.builtin.debug:
      var: _latest
  delegate_to: localhost
